import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Box, Typography } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <Box
          sx={{
            width: "100%",
            backgroundColor: "#0F0700",
            height: { xs: "100%", md: "330px" },
          }}
        >
          <Box
            sx={{
              maxWidth: { xs: "90%", md: "1500px" },
              margin: "auto",
              paddingTop: "40px",
              display: "flex",
              alignItems: "start",
              justifyContent: "space-between",
              flexWrap: "wrap",
              gap: { xs: "20px", md: "1px" },
            }}
          >
            {/* ///////// section */}
            <Box sx={{ width: { xs: "100%", md: "18%" } }}>
              <Box
                component="img"
                src="/pizzashop.png"
                alt="Pizza Shop"
                sx={{
                  width: "200px",
                  height: "auto",
                  borderRadius: 2,
                  objectFit: "cover",
                }}
              />
            </Box>
            <Box
              sx={{
                width: { xs: "45%", md: "18%" },
                display: "flex",
                flexDirection: "column",
                gap: "10px",
              }}
            >
              <Typography sx={{ fontSize: "25px", color: "#A3A3A3" }}>
                Home
              </Typography>
              <Typography sx={{ fontSize: "20px", color: "#515151" }}>
                To Order
              </Typography>
              <Typography sx={{ fontSize: "20px", color: "#515151" }}>
                About us
              </Typography>
              <Typography sx={{ fontSize: "20px", color: "#515151" }}>
                Events
              </Typography>
              <Typography sx={{ fontSize: "20px", color: "#515151" }}>
                Menu
              </Typography>
            </Box>
            {/* /// */}
            <Box
              sx={{
                width: { xs: "45%", md: "18%" },
                display: "flex",
                flexDirection: "column",
                gap: "10px",
              }}
            >
              <Typography sx={{ fontSize: "25px", color: "#A3A3A3" }}>
                Events
              </Typography>
              <Typography sx={{ fontSize: "20px", color: "#515151" }}>
                3 Pizza 1 Free Coffee
              </Typography>
              <Typography sx={{ fontSize: "20px", color: "#515151" }}>
                2 Pizza for 1 Price
              </Typography>
              <Typography sx={{ fontSize: "20px", color: "#515151" }}>
                Kitchen Tour
              </Typography>
            </Box>
            {/* ///////// */}
            <Box
              sx={{
                width: { xs: "45%", md: "18%" },
                display: "flex",
                flexDirection: "column",
                gap: "10px",
              }}
            >
              <Typography sx={{ fontSize: "25px", color: "#A3A3A3" }}>
                Menu
              </Typography>
              <Typography sx={{ fontSize: "20px", color: "#515151" }}>
                Show All
              </Typography>
              <Typography sx={{ fontSize: "20px", color: "#515151" }}>
                Seaproducts
              </Typography>
              <Typography sx={{ fontSize: "20px", color: "#515151" }}>
                Vegan
              </Typography>
              <Typography sx={{ fontSize: "20px", color: "#515151" }}>
                Meat
              </Typography>
            </Box>
            {/* /////// */}
            <Box
              sx={{
                width: { xs: "45%", md: "18%" },
                display: "flex",
                flexDirection: "column",
                gap: "10px",
              }}
            >
              <Typography sx={{ fontSize: "25px", color: "#A3A3A3" }}>
                About Us
              </Typography>
              <Typography sx={{ fontSize: "20px", color: "#515151" }}>
                Our History
              </Typography>
              <Typography sx={{ fontSize: "20px", color: "#515151" }}>
                Why We?
              </Typography>
            </Box>
          </Box>
          <Box
            sx={{
              maxWidth: { xs: "90%", md: "1500px" },
              margin: "auto",
              paddingTop: "35px",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
            }}
          >
            <Typography
              sx={{ fontSize: { xs: "23px", md: "25px" }, color: "#FF612E" }}
            >
              +7 (937) 333-55-33
            </Typography>
            <Box component="img" src="/socialImage.png" />
          </Box>
        </Box>
      </body>
    </html>
  );
}
